// <auto-generated />
namespace WebForms.AutoFac.MultiTenant.Data.Models.Tenants
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TenantUpdates12112020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TenantUpdates12112020));
        
        string IMigrationMetadata.Id
        {
            get { return "202012111741239_TenantUpdates-12-11-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
